<?php

use Illuminate\Database\Seeder;
use App\Models\Fabric\Subscription;

class SubscriptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        collect([
            [
                'name' => 'Pay as you go',
                'upgrade' => false,
                'services' => 20,
                'transactions' => null,
                'business_insights' => false,
                'api_keys' => 0,
                'sftp' => false,
                'users' => 1,
                'price' => 0,
                'sku' => 'CHRGB02',
                'product_type' => 'subscription',
            ],
            [
                'name' => 'Standard',
                'upgrade' => false,
                'services' => 20,
                'transactions' => 250_000,
                'business_insights' => false,
                'api_keys' => 0,
                'sftp' => false,
                'users' => 4,
                'price' => 50_000,
                'sku' => 'CHRGB04',
                'product_type' => 'subscription',
            ],
            [
                'name' => 'Professional',
                'upgrade' => false,
                'services' => 100,
                'transactions' => 500_000,
                'business_insights' => false,
                'api_keys' => 1,
                'sftp' => true,
                'users' => 12,
                'price' => 120_000,
                'sku' => 'CHRGB06',
                'product_type' => 'subscription',
            ],
            [
                'name' => 'Enterprise',
                'upgrade' => false,
                'services' => 100,
                'transactions' => 1_000_000,
                'business_insights' => false,
                'api_keys' => 1,
                'sftp' => true,
                'users' => 999,
                'price' => 200_000,
                'sku' => 'CHRGB077',
                'product_type' => 'subscription',
            ],
            [
                'name' => 'Base',
                'default' => true,
                'upgrade' => false,
                'services' => 200,
                'transactions' => 1_000_000,
                'business_insights' => false,
                'api_keys' => 0,
                'sftp' => false,
                'users' => 100,
                'price' => 0,
                'sku' => 'CHRGB0576',
                'product_type' => 'subscription',
            ],
            [
                'name' => 'Sandbox',
                'upgrade' => false,
                'services' => 2,
                'transactions' => 500,
                'business_insights' => false,
                'api_keys' => 0,
                'sftp' => false,
                'users' => 1,
                'price' => 0,
                'sku' => 'CHRGB01',
                'product_type' => 'subscription',
            ],
            [
                'name' => 'Business Insights Upgrade',
                'upgrade' => true,
                'services' => 0,
                'transactions' => 0,
                'business_insights' => true,
                'api_keys' => 0,
                'sftp' => false,
                'users' => 0,
                'price' => 0,
                'sku' => 'CHRGB054',
                'product_type' => 'bolton',
            ],
            [
                'name' => 'API Keys Upgrade',
                'upgrade' => true,
                'services' => 0,
                'transactions' => 0,
                'business_insights' => false,
                'api_keys' => 1,
                'sftp' => false,
                'users' => 0,
                'price' => 0,
                'sku' => 'CHRGB067',
                'product_type' => 'bolton',
            ],
            [
                'name' => 'Additional Services Upgrade',
                'upgrade' => true,
                'services' => 5,
                'transactions' => 0,
                'business_insights' => false,
                'api_keys' => 0,
                'sftp' => false,
                'users' => 0,
                'price' => 0,
                'sku' => 'CHRGB0199',
                'product_type' => 'bolton',
            ],
            [
                'name' => 'Additional Transactions Upgrade',
                'upgrade' => true,
                'services' => 0,
                'transactions' => 250_000,
                'business_insights' => false,
                'api_keys' => 0,
                'sftp' => false,
                'users' => 0,
                'price' => 0,
                'sku' => 'CHRGB0463',
                'product_type' => 'bolton',
            ],
            [
                'name' => 'Additional Users Upgrade',
                'upgrade' => true,
                'services' => 0,
                'transactions' => 0,
                'business_insights' => false,
                'api_keys' => 0,
                'sftp' => false,
                'users' => 6,
                'price' => 0,
                'sku' => 'CHRGB0986',
                'product_type' => 'bolton',
            ],
            [
                'name' => 'None',
                'upgrade' => false,
                'services' => 0,
                'transactions' => 0,
                'business_insights' => true,
                'api_keys' => false,
                'sftp' => false,
                'users' => 0,
                'price' => 0,
                'sku' => 'bi_none',
                'product_type' => 'bi_subscription',
            ],
            [
                'name' => 'Sandbox',
                'upgrade' => false,
                'services' => 0,
                'transactions' => 0,
                'business_insights' => true,
                'api_keys' => false,
                'sftp' => false,
                'users' => 0,
                'price' => 0,
                'sku' => 'bi_sandbox',
                'product_type' => 'bi_subscription',
            ],
            [
                'name' => 'Professional',
                'upgrade' => false,
                'services' => 0,
                'transactions' => 0,
                'business_insights' => true,
                'api_keys' => false,
                'sftp' => false,
                'users' => 0,
                'price' => 0,
                'sku' => 'bi_professional',
                'product_type' => 'bi_subscription',
            ],
            [
                'name' => 'Enterprise',
                'upgrade' => false,
                'services' => 0,
                'transactions' => 0,
                'business_insights' => true,
                'api_keys' => false,
                'sftp' => false,
                'users' => 0,
                'price' => 0,
                'sku' => 'bi_enterprise',
                'product_type' => 'bi_subscription',
            ]
        ])->each(function ($attributes) {
            Subscription::updateOrCreate(['sku' => $attributes['sku']], $attributes);
        });
    }
}
