name: Trigger Tests
on:
  workflow_dispatch:
    inputs:
      input:
        description: 'Specify input'
        required: true
        default: 'abc'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: convictional/trigger-workflow-and-wait@v1
        with:
          owner: gopatchworks
          repo: gopatchworks/patchworks-automation
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: run-tests.yml
          ref: development
          wait_interval: 10
          inputs: '{"test_parameters": "./tests/API/fabric/authentication"}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
